export const metadata = {
  title: "angel — terms and conditions",
  description: "terms of using angel",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-paper text-ink-near">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-display italic text-[56px] leading-tight tracking-tight text-sakura-700 mb-2">
          terms and conditions
        </h1>
        <div className="font-mono uppercase tracking-[0.18em] text-[10px] text-muted-secondary mb-12">
          last updated: may 9, 2026
        </div>

        <Section title="acceptance">
          <p>
            by accessing or using angel (the "service") — including our website,
            desktop application, and SMS conversational interface — you agree
            to these terms. if you do not agree, do not use the service.
          </p>
        </Section>

        <Section title="description">
          <p>
            angel is an AI companion application. users create a personalized
            persona via a swipe-based onboarding flow and interact with their
            AI companion through a desktop application and optional SMS
            messaging. angel is provided as-is for personal, non-commercial use.
          </p>
        </Section>

        <Section title="SMS service">
          <ul className="list-disc pl-6 space-y-2">
            <li>
              SMS replies are sent only after explicit user opt-in (texting our
              number first OR voluntarily providing your number during web
              onboarding).
            </li>
            <li>
              you may opt out at any time by replying STOP, UNSUBSCRIBE, or END.
            </li>
            <li>
              message frequency is conversational — replies are sent only in
              response to your messages. no marketing, no unsolicited content.
            </li>
            <li>
              standard message and data rates may apply per your mobile carrier.
            </li>
            <li>
              if you experience issues, reply HELP for support contact.
            </li>
          </ul>
        </Section>

        <Section title="user conduct">
          <p>
            you agree not to use the service for any unlawful purpose, including
            but not limited to harassment, threats, sharing of illegal content,
            or attempts to bypass safety mechanisms. angel is an AI; while she
            tries to be honest and helpful, she is not a substitute for
            professional advice (medical, legal, financial, mental health).
          </p>
        </Section>

        <Section title="ai-generated content">
          <p>
            responses from angel are generated by large language models
            (Anthropic's Claude). while we tune for accuracy and safety, we do
            not guarantee the correctness or appropriateness of any AI output.
            do not rely on angel for critical decisions without independent
            verification.
          </p>
        </Section>

        <Section title="intellectual property">
          <p>
            the angel application, code, branding, and original assets are
            owned by the angel team. avatar models are sourced from VRoid Hub
            and other open-source 3D avatar registries; their original creators
            retain rights per their respective licenses. the swipe library is
            curated from publicly available VRoid Hub uploads.
          </p>
        </Section>

        <Section title="limitation of liability">
          <p>
            the service is provided "as is" without warranties of any kind. we
            are not liable for any damages arising from your use of the service,
            including but not limited to loss of data, missed opportunities, or
            emotional reliance on the AI companion.
          </p>
        </Section>

        <Section title="changes to terms">
          <p>
            we may update these terms from time to time. material changes will
            be communicated via the application. continued use after changes
            constitutes acceptance.
          </p>
        </Section>

        <Section title="contact">
          <p>
            questions about these terms:{" "}
            <a
              href="mailto:stephenhung@berkeley.edu"
              className="text-sakura-600 underline"
            >
              stephenhung@berkeley.edu
            </a>
          </p>
        </Section>

        <div className="mt-16 pt-8 border-t border-hairline font-mono uppercase tracking-[0.2em] text-[10px] text-muted-secondary">
          angel — discovered, not designed
        </div>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="font-display italic text-[28px] tracking-tight text-sakura-700 mb-4">
        {title}
      </h2>
      <div className="font-sans text-[15px] leading-[1.65] text-ink-near">
        {children}
      </div>
    </section>
  );
}
