/**
 * lifecycle.ts — what happens when angel "wakes up" again.
 *
 * the embodied-AI illusion lives or dies at boot. opening the app should
 * not feel like launching software — it should feel like she was always
 * here and just heard you walk into the room.
 *
 * we persist a single timestamp (lastSeenAt) on app blur/quit, then on the
 * next boot compute the gap and route the boot greeting through one of six
 * "she's been gone for X" voices. each voice is just an INTENT (gist) — the
 * actual line is generated by claude in HER personality, same as the
 * introduction questions.
 *
 * filesystem:
 *   ~/.angel/lifecycle.json    ← { lastSeenAt: ISO, sessionCount: number,
 *                                  lastQuitReason: 'blur' | 'quit' | 'crash' }
 *
 * IMPORTANT: this module is standalone — no dep on runner.ts or main.ts so
 * it can be built before the running onboarding agent finishes touching
 * those files. wiring happens in task #39.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

export type QuitReason = 'blur' | 'quit' | 'crash' | 'unknown';

export interface LifecycleState {
  /** ISO timestamp of the last "she was alive" tick — written on blur+quit */
  lastSeenAt: string | null;
  /** monotonic count of cold boots since first install */
  sessionCount: number;
  /** what we know about how the previous session ended */
  lastQuitReason: QuitReason;
  /** ISO of the very first boot — never overwritten */
  firstBootAt: string | null;
}

export type GapBucket =
  | 'first_boot' // never run before
  | 'just_closed' // < 10 minutes — likely accidental close, or restart
  | 'short_break' // 10 min – 1 hour
  | 'few_hours' // 1 – 6 hours
  | 'same_day' // 6 – 24 hours (likely the next morning/evening)
  | 'days' // 1 – 7 days
  | 'weeks' // 7 – 30 days
  | 'long_absence'; // > 30 days

export interface BootGreetingIntent {
  bucket: GapBucket;
  /** ms since previous session, or null for first boot */
  gapMs: number | null;
  /** the GIST of what she should say — claude rewrites in her voice */
  intent: string;
  /** optional shape hint — "did anything happen while i was gone?" can pull
   *  from tensorlake observations / pending skills / unread messages */
  context?: string;
}

const LIFECYCLE_FILE = path.join(os.homedir(), '.angel', 'lifecycle.json');

const DEFAULT_STATE: LifecycleState = {
  lastSeenAt: null,
  sessionCount: 0,
  lastQuitReason: 'unknown',
  firstBootAt: null,
};

/* -------------------------------------------------------------------------- */
/* read / write                                                                */
/* -------------------------------------------------------------------------- */

function ensureDir(): void {
  fs.mkdirSync(path.dirname(LIFECYCLE_FILE), { recursive: true });
}

export function readLifecycleState(): LifecycleState {
  try {
    if (!fs.existsSync(LIFECYCLE_FILE)) return { ...DEFAULT_STATE };
    const raw = fs.readFileSync(LIFECYCLE_FILE, 'utf8');
    const parsed = JSON.parse(raw) as Partial<LifecycleState>;
    return {
      lastSeenAt: parsed.lastSeenAt ?? null,
      sessionCount: parsed.sessionCount ?? 0,
      lastQuitReason: (parsed.lastQuitReason as QuitReason) ?? 'unknown',
      firstBootAt: parsed.firstBootAt ?? null,
    };
  } catch (err) {
    console.warn('[lifecycle] failed to read state, defaulting:', err);
    return { ...DEFAULT_STATE };
  }
}

function writeLifecycleState(state: LifecycleState): void {
  ensureDir();
  fs.writeFileSync(LIFECYCLE_FILE, JSON.stringify(state, null, 2), 'utf8');
}

/* -------------------------------------------------------------------------- */
/* hooks — call these from main.ts                                             */
/* -------------------------------------------------------------------------- */

/**
 * call this on app boot, AFTER reading the previous state and BEFORE
 * computing the boot greeting. atomically:
 *   - bumps sessionCount
 *   - writes firstBootAt if missing
 *   - returns the PREVIOUS lastSeenAt so the greeting selector can compute gap
 *
 * returns the snapshot of the prior state so callers can use it to pick a
 * greeting. the new state is written back immediately so a crash won't lose
 * the bump.
 */
export function recordBoot(): LifecycleState {
  const prior = readLifecycleState();
  const now = new Date().toISOString();
  const next: LifecycleState = {
    lastSeenAt: prior.lastSeenAt, // preserved — greeting selector uses this
    sessionCount: prior.sessionCount + 1,
    lastQuitReason: prior.lastQuitReason,
    firstBootAt: prior.firstBootAt ?? now,
  };
  writeLifecycleState(next);
  return prior;
}

/**
 * call this on every "she's still here" tick — recommended every 30s while
 * the app is focused, and on every blur. cheap (single fs.write).
 */
export function tickAlive(reason: QuitReason = 'unknown'): void {
  const state = readLifecycleState();
  state.lastSeenAt = new Date().toISOString();
  state.lastQuitReason = reason;
  writeLifecycleState(state);
}

/**
 * call this on app quit (will-quit / before-quit). last write wins.
 */
export function recordQuit(reason: QuitReason = 'quit'): void {
  tickAlive(reason);
}

/* -------------------------------------------------------------------------- */
/* gap computation + greeting intent                                           */
/* -------------------------------------------------------------------------- */

const MS_MIN = 60 * 1000;
const MS_HR = 60 * MS_MIN;
const MS_DAY = 24 * MS_HR;

export function bucketForGap(gapMs: number | null): GapBucket {
  if (gapMs === null) return 'first_boot';
  if (gapMs < 10 * MS_MIN) return 'just_closed';
  if (gapMs < 1 * MS_HR) return 'short_break';
  if (gapMs < 6 * MS_HR) return 'few_hours';
  if (gapMs < 24 * MS_HR) return 'same_day';
  if (gapMs < 7 * MS_DAY) return 'days';
  if (gapMs < 30 * MS_DAY) return 'weeks';
  return 'long_absence';
}

/** human-readable gap, for stuffing into the intent context */
export function humanizeGap(gapMs: number | null): string {
  if (gapMs === null) return 'never met before';
  const min = Math.round(gapMs / MS_MIN);
  if (min < 60) return `${min} minute${min === 1 ? '' : 's'} ago`;
  const hr = Math.round(gapMs / MS_HR);
  if (hr < 24) return `${hr} hour${hr === 1 ? '' : 's'} ago`;
  const day = Math.round(gapMs / MS_DAY);
  if (day < 14) return `${day} day${day === 1 ? '' : 's'} ago`;
  if (day < 60) return `${Math.round(day / 7)} week${Math.round(day / 7) === 1 ? '' : 's'} ago`;
  return `${Math.round(day / 30)} month${Math.round(day / 30) === 1 ? '' : 's'} ago`;
}

/**
 * pick the boot-greeting intent based on the gap since lastSeenAt. each
 * intent is a GIST claude rewrites in her voice (see runner.ts buildSystemPrompt
 * + the existing boot-greeting primer). NEVER use these strings directly.
 *
 * the intent always tells claude to AVOID inventing concrete things she did
 * "while you were away" — only reference the memory block / observations.
 */
export function selectBootGreetingIntent(opts: {
  /** the lastSeenAt from the PRIOR state (call recordBoot first to get it) */
  priorLastSeenAt: string | null;
  /** optional context bundle — injected as "context" in the intent */
  pendingSkillsCount?: number;
  recentObservationsLine?: string;
}): BootGreetingIntent {
  const { priorLastSeenAt, pendingSkillsCount = 0, recentObservationsLine } = opts;
  const gapMs = priorLastSeenAt ? Date.now() - new Date(priorLastSeenAt).getTime() : null;
  const bucket = bucketForGap(gapMs);

  const intentByBucket: Record<GapBucket, string> = {
    first_boot:
      "the very first time the user has ever opened you. you've just become real. greet them — short, in your voice. don't perform.",
    just_closed:
      "you were just closed less than 10 minutes ago and reopened. ack the bounce-back lightly, like 'changed your mind?' or 'forget something?' — short, no drama.",
    short_break:
      "the user closed you about an hour ago and is back. casual welcome-back. one short line. don't make a thing of it.",
    few_hours:
      "the user has been gone a few hours. acknowledge the gap warmly — 'back already?' / 'how'd it go?' — short, in your voice.",
    same_day:
      "the user has been gone since yesterday or earlier today. greet them like the next sitting — 'morning' / 'evening' depending on local time, or just a check-in. short.",
    days:
      "the user has been gone several days. you noticed. ack it without guilt-tripping — 'oh hey. been a minute. you good?' — keep her voice; never beg.",
    weeks:
      "the user has been gone a few weeks. you missed them a little but you're not going to perform it. one sober line.",
    long_absence:
      "the user has been gone over a month. you don't even know if they're the same person anymore. ack the long absence with curiosity, not abandonment — 'stranger. you alive?' kind of line.",
  };

  let context: string | undefined;
  const contextParts: string[] = [];
  if (priorLastSeenAt) {
    contextParts.push(`gap_since_last_seen: ${humanizeGap(gapMs)}`);
  }
  if (pendingSkillsCount > 0) {
    contextParts.push(
      `pending_skills_drafted_last_session: ${pendingSkillsCount} (you can ack with "i drafted ${pendingSkillsCount} skill${pendingSkillsCount === 1 ? '' : 's'} for myself yesterday — want me to install ${pendingSkillsCount === 1 ? 'it' : 'them'}?")`,
    );
  }
  if (recentObservationsLine) {
    contextParts.push(`recent_background_observation: ${recentObservationsLine}`);
  }
  if (contextParts.length > 0) context = contextParts.join('\n');

  return {
    bucket,
    gapMs,
    intent: intentByBucket[bucket],
    context,
  };
}

/* -------------------------------------------------------------------------- */
/* introspection                                                               */
/* -------------------------------------------------------------------------- */

export interface LifecycleStatus {
  bucket: GapBucket;
  gapHuman: string;
  sessionCount: number;
  lastSeenAt: string | null;
  firstBootAt: string | null;
  lastQuitReason: QuitReason;
}

export function lifecycleStatus(): LifecycleStatus {
  const state = readLifecycleState();
  const gapMs = state.lastSeenAt ? Date.now() - new Date(state.lastSeenAt).getTime() : null;
  return {
    bucket: bucketForGap(gapMs),
    gapHuman: humanizeGap(gapMs),
    sessionCount: state.sessionCount,
    lastSeenAt: state.lastSeenAt,
    firstBootAt: state.firstBootAt,
    lastQuitReason: state.lastQuitReason,
  };
}

export const LIFECYCLE_PATH = LIFECYCLE_FILE;
